# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0008_auto_20150509_1557'),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_to_win', models.SmallIntegerField(default=16)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Device')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answer_one', models.CharField(max_length=100)),
                ('incorrect_answer_two', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=3)),
                ('lang', models.CharField(choices=[(b'es', b'Espa\xc3\xb1ol'), (b'eu', b'Euskara'), (b'pl', b'Polako')], max_length=5)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.DateField(auto_now_add=True)),
                ('reviewed', models.BooleanField()),
                ('public', models.BooleanField()),
                ('photo_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='gamequestionstatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
    ]
