# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestionstatus',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
