# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20151218_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
