# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('claimed', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event', models.BooleanField()),
                ('total', models.SmallIntegerField()),
                ('available', models.SmallIntegerField()),
                ('valid_until', models.DateField()),
                ('muste_claim_days_delta', models.SmallIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='deviceprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.Price'),
        ),
    ]
