# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='muste_claim_days_delta',
            new_name='must_claim_days_delta',
        ),
    ]
