# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20160108_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='title',
            new_name='title_eu',
        ),
        migrations.AddField(
            model_name='price',
            name='info_en',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='info_es',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='info_eu',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='title_en',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='title_es',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
