# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20160120_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='info_en',
            new_name='url_en',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='info_es',
            new_name='url_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='info_eu',
            new_name='url_eu',
        ),
        migrations.AlterField(
            model_name='price',
            name='must_claim_days_delta',
            field=models.SmallIntegerField(verbose_name=b'Ez da ebentoa: zenbat egun iraungi arte?'),
        ),
        migrations.AlterField(
            model_name='price',
            name='valid_until',
            field=models.DateField(verbose_name=b'Noiz da ebentoa?'),
        ),
    ]
