# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlpanel',
            old_name='difficulty',
            new_name='difficulty_max',
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='difficulty_min',
            field=models.SmallIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='language',
            field=models.CharField(choices=[(b'es', b'Espa\xc3\xb1ol'), (b'eu', b'Euskara'), (b'en', b'English')], max_length=5),
        ),
    ]
