# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20161024_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanel',
            name='partida_kopurua_max',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='partida_kopurua_min',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='zenbat_egunez_partidak',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='zenbat_egunez_saria',
            field=models.SmallIntegerField(default=30),
        ),
    ]
